name: Manual Builds

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Name'
        required: true
        default: 'Prismatic Factory Update'
      ver:
        description: 'Version'
        required: true
        default: '1.11.124'
      desc:
        description: 'Description'
        required: true
        default: 'Adds lots of new content like the d-compressor'

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH

    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16

    - name: Build mod jar
      run: ./gradlew deploy

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.ver }}
        release_name: ${{ github.event.inputs.release }}
        body: ${{ github.event.inputs.desc }}
        draft: false
        prerelease: false

    - name: Upload Assets
      uses: actions/upload-release-asset@v1

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/${{ github.event.repository.name }}.jar
        asset_name: Prismatic.jar
        asset_content_type: application/zip
